package com.example.countryapp

object CountryData {
    private val countryName = arrayOf("Indonesia", "Amerika Serikat", "Mesir", "China", "Inggris", "Jerman", "Prancis", "Palestina", "Jepang", "Korea Selatan")
    private val countryDetails = arrayOf("Indonesia adalah negara kepulauan terbesar di dunia. Indonesia memiliki lebih dari 17.000 pulau, di mana hanya sekitar 7.000 pulau yang berpenghuni. Kalimantan, Jawa, Sulawesi, Sumatra dan Papua merupakan pulau utama di Indonesia. Selain itu Indonesia juga memiliki pulau-pulau kecil seperti Bali, Karimunjawa, Gili dan Lombok yang merupakan tujuan wisata lokal maupun internasional. Ibukota negara Indonesia adalah Jakarta, yang terletak di Pulau Jawa. Selain pulau-pulau yang indah, iklim tropis yang dimiliki Indonesia juga menjadikan Indonesia menjadi tujuan wisata yang utama. Waktu terbaik untuk berwisata ke Indonesia adalah saat musim panas yang berlangsung mulai bulan April hingga Oktober. Bulan Maret dan November merupakan pergantian musim. Pada pergantian musim, cuaca di Indonesia dapat menjadi tidak menentu. Hujan, panas matahari dan angin lebat dapat datang bersamaan dalam satu hari. Sementara itu, musim hujan biasanya berlangsung mulai bulan Desember hingga Maret.",
        "Amerika Serikat, disingkat dengan AS, atau secara umum dikenal dengan Amerika saja, adalah sebuah negara republik konstitusional federal yang terdiri dari lima puluh negara bagian dan sebuah distrik federal. Negara ini terletak di bagian tengah Amerika Utara, yang menjadi lokasi dari empat puluh delapan negara bagian yang saling bersebelahan, beserta distrik ibu kota Washington, D.C.. Amerika Serikat diapit oleh Samudra Pasifik dan Atlantik di sebelah barat dan timur, berbatasan dengan Kanada di sebelah utara, dan Meksiko di sebelah selatan. Dua negara bagian lainnya, yaitu Alaska dan Hawaii, terletak terpisah dari dataran utama Amerika Serikat. Negara bagian Alaska terletak di sebelah ujung barat laut Amerika Utara, berbatasan dengan Kanada di sebelah timur dan Rusia di sebelah barat, yang dipisahkan oleh Selat Bering. Sedangkan negara bagian Hawaii adalah sebuah kepulauan yang berlokasi di Samudra Pasifik. Amerika Serikat juga memiliki beberapa teritori di Pasifik dan Karibia.",
    "Mesir atau dalam bahasa Inggris disebut dengan Egypt adalah sebuah negara yang terletak di dua benua (trans-benua) yaitu benua Afrika dan benua Asia. Negara dengan nama lengkap Republik Arab Mesir ini sebagian besar wilayahnya terletak di bagian timur laut Afrika sehingga sering digolongkan sebagai negara yang berada di benua Afrika. Berbagai media dan organisasi internasional juga sering menggolongkan Mesir sebagai negara yang berada di kawasan Timur Tengah. Secara geografis, Mesir yang memiliki luas wilayah 1.001.450 km2 ini berbatasan dengan Libya di sebelah barat dan Sudan di sebelah Selatan, sedangkan di sebelah timur Mesir adalah Jalur Gaza dan Israel. Mesir juga berbatasan laut dengan Laut Tengah di sebelah utara dan Laut Merah di sebelah timur. Secara Astronomis, Mesir terletak di antara  25°BT- 36°BT dan 22°LU- 32°LU. Ibukota Mesir berada di Kota Kairo.",
    "China atau Tiongkok adalah Negara dengan Jumlah Penduduk Terbanyak di Dunia. Jumlah Penduduk China yang sebanyak 1,38 miliar jiwa (2018) ini sekitar 5 kali lipat lebih banyak dari populasi Indonesia yang berjumlah sekitar 262 juta jiwa (2018). Selain sebagai Negara yang memiliki penduduk terbanyak di Dunia, China juga merupakan salah satu Negara Terbesar di Dunia dengan Luas wilayahnya sebesar 9.596.960km2. Luas wilayah ini menjadikan China sebagai Negara Terbesar ke-4 di dunia. Secara geografis, China atau Tiongkok terletak di Benua Asia bagian Timur (Asia Timur) dan berada di antara 18° LU – 54° LU dan 73° BT – 135° BT. China berbatasan dengan Mongolia di sebelah Utaranya sedangkan di sebelah Selatannya berbatasan dengan Nepal, Bhutan, India, Myanmar, Laos dan Vietnam. Di Sebelah Timur China berbatasan dengan Korea Utara dan sebelah Barat berbatasan dengan Pakistan, Kirghistan, Kazakhtan dan Tajikistan.",
    "Inggris merupakan negara yang berbentuk kerajaan konstitusional, disebut juga United Kingdom atau Britania Raya. Inggris pernah dipimpin oleh seorang perdana menteri wanita bernama Margareth Thatcher yang dijuluki sebagai wanita bertangan besi. Terletak antara 49 derajat LU- 59,5 derajat LU dan 11 derajat BB – 2derajat BT. Inggris beriklim laut sedang yang dipengaruhi oleh arus atlantik Utara yang hangat, sehingga rata-rata suhu di beberapa daerah yang terletak di bagian utara lebih tinggi dibanding di daerah lain yang terletak pada lintang yang sama. Penduduk Inggris tahun 1988 berjumlah 56.80 juta jiwa, dan sekarang sudah mencapai 80,2 juta jiwa, sekitar 75% tinggal di kota-kota. Imigrasi menyebabkan Inggris dihuni oleh berbagai bangsa. Inggris merupakan negara industri terkemuka di Eropa di samping Jerman Barat. Hasil industri yang utama adalah tekstil, baja, kereta api, alat elektronik, alat pertanian, kimia dan mainan anak-anak.",
    "Jerman adalah sebuah negara yang terletak di benua Eropa dengan bentuk pemerintahan Republik Federal Parlementer. Jerman pernah terpecah menjadi dua negara karena kalah pada Perang Dunia kedua, bagian barat Jerman yang dikuasai oleh sekutu Perancis, Inggris and Amerika Serikat ini kemudian pada tanggal 23 Mei 1949 membentuk negara baru dengan sebutan Republik Federal Jerman (Bundesrepublik Deutschland) dengan ibukotanya di Bonn sedangkan bagian Timur Jerman yang dikuasai oleh Uni Soviet dan membentuk negara baru pada tanggal 7 Oktober 1949 dengan sebutan Republik Demokratik Jerman (Deutsche Demokratische Republik) dan beribukota di Berlin. Namun kedua negara tersebut berhasil bersatu kembali menjadi satu negara dengan nama Republik Federal Jerman  pada tanggal 3 Oktober 1990. Tanggal 3 Oktober ini kemudian diperingati sebagai Hari Persatuan Jerman. Setelah penyatuan kembali, Ibukota Jerman ditetapkan di Kota Berlin.",
    "Perancis adalah Negara yang terletak di Benua Eropa tepatnya di Eropa bagian Barat. Selain Teritori Metropolitan yang berada di Benua Eropa, Perancis juga memiliki beberapa pulau dan teritori di seberang laut yang berada di Benua lainnya. Luas wilayah Perancis secara keseluruhan adalah 643.801km2, luas wilayah ini termasuk Metropolitan Perancis seluas 551.500km2 dan Teritori seberang laut seluas 92.301km2. Teritori seberang laut tersebut diantaranya adalah French Guiana di Amerika Selatan, Guadeloupe dan Martinique di Laut Karabia Amerika Tengah, Mayotte dan Reunion di Samudera Hindia. Di Eropa, Metropolitan Perancis berbatasan dengan Swiss, Italia dan Jerman di sebelah Timur sedangkan sebelah Barat adalah Teluk Biscay. Di Utara Metropolitan Perancis adalah Selat Channel (selat yang memisahkan daratan Eropa dengan Inggris) dan Belgia. Di sebelah Selatannya, Metropolitas Perancis berbatasan dengan Spanyol dan Laut Mediterania. Secara Astronomis, Perancis terletak diantara 42°LU – 51°LU dan 5°BB – 8°BT.",
    "Palestina merupakan negara yang berada di wilayah Timur Tengah. Wilayah Timur Tengah dikenal dengan kawasan yang kaya akan minyak bumi. Wilayah Palestina dari sudut pandang geografis sangat strategis, dan menjadi penghubung tiga benua, yaitu Asia, Afrika dan Eropa. Justru karena letak strategis tersebut, konflik menjadi rawan muncul. Seperti halnya konflik Palestina dan Israel yang masih berlangsung sampai dengan tahun 2021 ini. Palestina memiliki wilayah yang terletak di Mediterania Timur. Menurut visi Otoritas Palestina tentang solusi status akhir dengan Israel, wilayah Negara Palestina meliputi Yerusalem Timur, Tepi Barat dan Jalur Gaza. Tepi Barat memiliki luas wilayah sekitar 5.655 km2, sedangkan luas Jalur Gaza sekitar 365 km2. Tepi Barat dan Jalur Gaza terletak di bagian Timur Laut Mediterania. Sehingga iklim yang ada di negara Palestina adalah iklim Mediterania yang ditandai dengan musim panas yang kering dan panas, dan musim dingin yang ringan dan basah. Suhu rata-rata sekitar 19 ºC, dengan suhu tertinggi mencapai 40 ºC pada bulan Juni dan terendah pada bulan Januari. Curah hujan terjadi di musim gugur dan musim dingin yang ukurannya sekitar 400 milimeter per tahun.",
    "Jepang adalah sebuah negara Kepulauan yang terletak di Benua Asia bagian Timur (Asia Timur). Sebagai Negara Kepulauan, Jepang memiliki sekitar 6.852 pulau besar maupun kecil. Pulau-pulau utama Jepang diantaranya adalah Pulau Hokkaido, Pulau Honshu, Pulau Shikoku dan Pulau Kyushu. Jepang juga merupakan salah satu negara yang memiliki garis pantai terpanjang di dunia yaitu sekitar 29.751 km2. Pulau Honshu merupakan pulau Terbesar di Jepang. Ibukota Jepang yaitu Kota Tokyo terletak di Pulau Honshu ini. Saat ini, Jepang merupakan Negara yang menduduki urutan ketiga sebagai Negara dengan Ekonomi terbesar setelah Amerika Serikat dan China (Tiongkok). Pendapatan Domestik Bruto atau PDB Nomimal Jepang adalah US\$ 5,231 triliun dengan Pendapatan Per Kapita sebesar US\$41.429,- pada tahun 2019. Namun saat ini Jepang juga mengalami permasalahan penurunan jumlah penduduk, angka kelahiran Jepang hanya mencapai 7 bayi per 1000 penduduk sedangkan angka kematiannya adalah 11,44 kematian per 1000 penduduk. Secara geografis, Jepang yang tidak ada perbatasan darat dengan negara lain ini terletak di antara 30° LU – 47° LU dan 128° BT – 146° BT. Sebelah Timur Kepulauan Jepang adalah Benua Asia (Korea Selatan, Korea Utara, Tiongkok dan Rusia) sedangkan di sebelah Baratnya adalah Samudra Pasifik.",
    "Korea Selatan adalah negara yang terletak di semenanjung Korea, Asia Timur.  Semenanjung Korea yang sebelumnya merupakan wilayah untuk satu negara yaitu negara Korea yang saat ini terpisah menjadi dua negara (Korea Selatan dan Korea Utara) karena perang saudara. Korea Selatan membentuk negara tersendiri dan menamakannya sebagai Republik Korea (Republik of Korea) pada tahun 1948. Korea Selatan menganut sistem pemerintahan Republik Presidensil. Berdasarkan sistem Presidensil yang dianut oleh Korea Selatan ini, Kepala Negara dan Kepala Pemerintahan dijabat oleh seorang Presiden yang dipilih oleh rakyat berdasarkan hasil Pemilihan Umum untuk masa jabatan 5 tahun. Luas wilayah Korea Selatan yang sebesar 99,720km2 ini berada di antara 124°BT- 130°BT dan 33°LU- 39°LU. Secara geografis, Korea Selatan berbatasan darat dengan Korea Utara disebelah utaranya sedangkan sebelah timur, selatan dan barat dikeliling oleh laut. Di sebelah barat dan selatan adalah Laut Kuning dan sebelah barat adalah laut Jepang sedangkan di sebelah tenggaranya adalah selat Korea yang berbatasan dengan Jepang.")
    private val countryCapitalCity = arrayOf("DKI Jakarta","Washington, D.C.", "Kairo", "Beijing", "London", "Berlin", "Paris", "Yerussalem", "Tokyo", "Seoul")
    private val countryNationalLanguage = arrayOf("Indonesia", "Inggris", "Arab", "Mandarin", "Inggris", "Jerman", "Prancis", "Arab", "Jepang", "Korea")
    private val countryIndependenceDay = arrayOf("17 Agustus", "4 Juli", "18 Juni", "1 Oktober", "23 April", "3 Oktober", "14 Juli", "15 November", "11 Februari", "15 Agustus")
    private val countryWideRegion = arrayOf("7,81 juta km2","9,834 juta km²", "1010407 km2", "9596961 km2", " 244.046 km2", "357,386 km2", "543.940 km²", "6.020 km2", "377,974 km2", "100,363 km2")
    private val countryImages = intArrayOf(R.drawable.indo_flag, R.drawable.america_flag, R.drawable.mesir_flag, R.drawable.china_flag, R.drawable.england_flag, R.drawable.german_flag, R.drawable.france_flag, R.drawable.palestine_flag, R.drawable.japan_flag, R.drawable.south_korea_flag)

    val listData: ArrayList<Country>
        get() {
            val list = arrayListOf<Country>()
            for(position in countryName.indices) {
                val country = Country()
                country.name = countryName[position]
                country.detail = countryDetails[position]
                country.photo = countryImages[position]
                country.capitalCity = countryCapitalCity[position]
                country.nationalLanguage = countryNationalLanguage[position]
                country.independenceDay = countryIndependenceDay[position]
                country.wideRegion = countryWideRegion[position]
                list.add(country)
            }
            return list
        }
}